Repository plone/buildout.coredev, pull requests merged in 2018-05, with the labels that each got.

#472 Use zc.buildout 2.11.4 [5.2]
  requirements.txt
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing

#463 Use Zope2 2.13.28 [4.3]
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review

#474 Remove plips/cmf-merge.cfg plips/plip-1334-PlonePAS.cfg
  plips/cmf-merge.cfg
  plips/plip-1334-PlonePAS.cfg
Labels: 04 type: enhancement, 13 prio: normal, 32 needs: review

#478 5.2 update branches
  sources.cfg
  versions.cfg
Labels: 24 status: ready

#479 Pin Chameleon in such a way that mr.developer can unpin it
  versions.cfg
Labels: 24 status: ready
