Repository plone/buildout.coredev, pull requests merged in 2018-04, with the labels that each got.

#446 Update version of pytz to 2018.03 (trial 2)
  versions.cfg
Labels: 04 type: enhancement, 23 status: testing

#448 Checkout zc.relation and zc.relationship from the proper repo
  py3.cfg
Labels: 04 type: enhancement, 22 status: in-progress, 35 needs: rebase

#458 Update zope.app.locales
  versions.cfg
Labels: 04 type: enhancement, 24 status: ready, 32 needs: review, 99 tag: Plone 4.3.x

#460 zope.ramcache 2.2.0
  versions.cfg
Labels: 04 type: enhancement, 24 status: ready, 32 needs: review, 99 tag: Plone 4.3.x

#461 zope.ramcache 2.2.0
  versions.cfg
Labels: 04 type: enhancement, 24 status: ready, 32 needs: review, 99 tag: Plone 5.x

#464 Use fresh Zope 4.0b4.
  versions.cfg
Labels: 04 type: enhancement, 11 prio: blocker, 23 status: testing, 32 needs: review

#466 Pin Products.ZCatalog back to 4.0.1.
  sources.cfg
  versions.cfg
Labels: 02 type: regression, 12 prio: high, 23 status: testing
