Repository plone/buildout.coredev, pull requests merged in 2018-03, with the labels that each got.

#421 Use Zope2 2.13.27 and friends. [4.3]
  versions.cfg
Labels: 04 type: enhancement, 11 prio: blocker, 24 status: ready, 32 needs: review

#422 Use Zope2 2.13.27 and friends. [5.0]
  versions.cfg
Labels: 01 type: bug, 11 prio: blocker, 24 status: ready, 32 needs: review

#423 Use Zope2 2.13.27 and friends. [5.1]
  versions.cfg
Labels: 01 type: bug, 11 prio: blocker, 24 status: ready, 32 needs: review

#444 update versions
  tests.cfg
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing
