Repository plone/buildout.coredev, pull requests merged in 2018-07, with the labels that each got.

#502 Cleanup versions and update
  core.cfg
  tests.cfg
  versions.cfg
Labels: 04 type: enhancement, 23 status: testing

#506 remove obsolete version pins
  versions.cfg
Labels: 04 type: enhancement, 23 status: testing

#508 Update six to 1.11.0
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review, 99 tag: Plone 4.3.x

#507 Update six to 1.11.0
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review, 99 tag: Plone 5.x
