Repository plone/buildout.coredev, pull requests merged in 2019-09, with the labels that each got.

#603 Use Zope 4.1.2.
  checkouts.cfg
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing, 32 needs: review

#604 generate constraints.txt
  core.cfg
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing

#606 Upgrade to Zope2 2.13.29 and Products.ZCatalog 2.13.30. [4.3.x]
  versions.cfg
Labels: 04 type: enhancement, 12 prio: high, 23 status: testing, 32 needs: review

#608 Upgrade the requests package to match the one in the 5.2 branch
  versions.cfg
Labels: 24 status: ready
