Repository plone/buildout.coredev, pull requests merged in 2020-02, with the labels that each got.

#631 Update DocumentTemplate and Products.ZSQLMethods for hotfix [4.3]
  versions.cfg
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing

#633 Update DocumentTemplate and Products.ZSQLMethods for hotfix. [5.2]
  versions.cfg
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing, 32 needs: review

#632 Update DocumentTemplate and Products.ZSQLMethods for hotfix. [5.1]
  versions.cfg
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing, 32 needs: review

#641 DocumentTemplate = 3.2.2.
  versions.cfg
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing

#643 update versions (3rd party)
  requirements.txt
  tests.cfg
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing
