Repository plone/buildout.coredev, pull requests merged in 2020-08, with the labels that each got.

#668 Fix windows
  .github/workflows/run-buildout.yml
  checkouts.cfg
  core.cfg
  requirements.txt
  sources.cfg
  versions.cfg
Labels: 02 type: regression, 12 prio: high, 22 status: in-progress

#671 Use Zope 4.5.1 (and no other changes)
  versions.cfg
Labels: 04 type: enhancement, 11 prio: blocker, 23 status: testing, 32 needs: review

#672 Updated various versions to bugfixes. [4.3]
  versions.cfg
Labels: 01 type: bug, 12 prio: high, 23 status: testing, 32 needs: review

#673 Updated various versions. [5.1]
  requirements.txt
  tests.cfg
  versions.cfg
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review
