Repository plone/buildout.coredev, pull requests merged in 2021-02, with the labels that each got.

#693 Uses TZ = UTC in buildout
  tests.cfg
Labels: 01 type: bug, 05 type: question, 14 prio: low, 22 status: in-progress, 32 needs: review

#705 New branches after templates have been converted to bootstrap 5
  sources.cfg
Labels: 24 status: ready

#706 New branches after templates have been converted to bootstrap 5
  sources.cfg
Labels: 24 status: ready

#709 5.2: Use Zope 4.5.4 versions.
  versions.cfg
Labels: 04 type: enhancement, 12 prio: high
